obj-$(CONFIG_SENSORS)		+= sensors_class.o
obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o

# acclerometer_sensor
obj-$(CONFIG_SENSORS_K2HH)          += k2hh.o

# optical_sensor
obj-$(CONFIG_SENSORS_STK3013)	+= stk3013.o
